### ISSUE TITLE
Make sdclientapi installable via pip

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/sdclientapi#3]
We want this SDK to be used by:

- [SecureDrop Qubes Qt client](https://github.com/freedomofpress/securedrop-client)
- Someday (perhaps) other news organizations who want to implement their own tooling

Such that we can easily use it as a dependency in both situations, I think it would make sense for this to be pip installable.

**Comment by kushaldas** [comment]
>Such that we can easily use it as a dependency in both situations, I think it would make sense for this to be pip installable.

:+1:  to that. I never wrote a `setup.py` as I am using it right now for more of a local development environment.

**Comment by kushaldas** [comment]
I guess we can close this issue as we are now ready for a formal release whenever we want. @redshiftzero what do you think?

**Comment by redshiftzero** [comment]
yep since #8 was merged this is indeed true, we can hold off on uploading to PyPI until we are ready for the first release. Closing!
