### ISSUE TITLE
Update SDK for reply endpoints

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/sdclientapi#4]
Over in https://github.com/freedomofpress/securedrop/pull/3700 there are some API changes that enable journalists to get information about, download, and delete replies from sources. We should update the code for these changes and add tests.

**Comment by kushaldas** [comment]
We will have to wait till the server side API is stable.

**Comment by redshiftzero** [comment]
(no longer blocked, the server-side PR was merged)
